language: node_js
node_js:
  - node
script: npm run test:unit && npm run build --fix
deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: "marqetplace-staging"
    local-dir: dist
    acl: public_read
    on:
      branch: staging
  - provider: s3
    skip_cleanup: true
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: "marqetplace-production"
    local-dir: dist
    acl: public_read
    on:
      branch: master
